<Project Sdk="MSTest.Sdk">
    
    <PropertyGroup>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <LangVersion>preview</LangVersion>
        <TargetFramework>net10.0</TargetFramework>
    </PropertyGroup>
    
    <ItemGroup>        
        <ProjectReference Include="..\MageeSoft.PDX.CE\MageeSoft.PDX.CE.csproj"/>
        <ProjectReference Include="..\MageeSoft.PDX.CE.Cli\MageeSoft.PDX.CE.Cli.csproj" />
    </ItemGroup>
    
    <ItemGroup>      
      <Content Include="TestData/**/*.*">
        <CopyToOutputDirectory>Always</CopyToOutputDirectory>
      </Content>
    </ItemGroup>
    
</Project>