namespace MageeSoft.PDX.CE.SourceGenerator;

/// <summary>
/// Helper for generating the model files.
/// </summary>
internal static class ModelGenerationHelper
{
    /// <summary>
    /// The fully qualified name of the attribute.
    /// </summary>
    public const string AttributeName = "MageeSoft.PDX.CE.GameStateDocumentAttribute";

    /// <summary>
    /// The source code for the attribute class.
    /// </summary>
    public readonly static string Attribute = """
      // <auto-generated/>
      using System;
      using System.Collections.Generic;

      namespace MageeSoft.PDX.CE
      {
          /// <summary>
          /// Marks a class as a game state document that will have its model generated from a schema file.
          /// </summary>
          [AttributeUsage(AttributeTargets.Class, Inherited = false, AllowMultiple = false)]
          public sealed class GameStateDocumentAttribute : Attribute
          {
              /// <summary>
              /// Creates a new instance of the attribute.
              /// </summary>
              /// <param name="schemaFileName">The name of the schema file to use for generating the model.</param>
              public GameStateDocumentAttribute(string schemaFileName)
              {
                  SchemaFileName = schemaFileName;
              }

              /// <summary>
              /// Gets the name of the schema file to use for generating the model.
              /// </summary>
              public string SchemaFileName { get; }
          }
      }
      """;
}