name: Build & Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest    
    steps:
    
    - uses: actions/checkout@v3
      with:
        fetch-depth: 0    # Fetch all history for GitVersion
    
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x
    
    - name: Restore dependencies
      run: dotnet restore ./src/MageeSoft.Paradox.Clausewitz.Save.slnx      

    - name: Build
      run: dotnet build ./src/MageeSoft.Paradox.Clausewitz.Save.slnx --no-restore    

    - name: Test
      run: dotnet test ./src/MageeSoft.Paradox.Clausewitz.Save.slnx --no-build --verbosity normal