name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Fetch all history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Restore dependencies
      run: dotnet restore ./src/MageeSoft.Paradox.Clausewitz.Save.slnx

    - name: Build
      run: dotnet build ./src/MageeSoft.Paradox.Clausewitz.Save.slnx --no-restore

    - name: Test with coverage
      run: dotnet test ./src/MageeSoft.Paradox.Clausewitz.Save.slnx --no-build --verbosity normal /p:CollectCoverage=true /p:CoverletOutputFormat=opencover /p:CoverletOutput="./coverage.opencover.xml"

    - name: Upload coverage reports to Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: pjmagee/paradox-clausewitz-save
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: false
        files: ./src/MageeSoft.Paradox.Clausewitz.Save.Tests/coverage.opencover.xml
