name: Code Coverage

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0    # Fetch all history for GitVersion

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 10.0.x

    - name: Test with coverage
      run: |
        cd ./src/MageeSoft.PDX.CE.Tests
        dotnet run --coverage --coverage-output $GITHUB_WORKSPACE/report.cobertura.xml  --coverage-output-format cobertura

    - name: ReportGenerator
      uses: danielpalme/ReportGenerator-GitHub-Action@5.2.0
      with:
        reports: '${{ github.workspace }}/report.cobertura.xml'
        targetdir: '${{ github.workspace }}/coveragereport'
        reporttypes: 'MarkdownSummaryGithub'

    - name: Upload coverage - GitHub
      run: cat $GITHUB_WORKSPACE/coveragereport/SummaryGithub.md >> $GITHUB_STEP_SUMMARY

    - name: Upload coverage - Codecov
      uses: codecov/codecov-action@v5
      env:
        CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        slug: pjmagee/paradox-clausewitz-save
        name: codecov-umbrella
        fail_ci_if_error: true
        verbose: false
        files: ${{ github.workspace }}/report.cobertura.xml
