name: Build and Publish Native Executables

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build native executables for Windows
        run: .\etc\build-native-windows.ps1     
      - name: Upload Windows x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/win-x64/stellaris-sav-win-x64.zip
          asset_name: stellaris-sav-win-x64.zip
          asset_content_type: application/zip
      - name: Upload Windows ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/win-arm64/stellaris-sav-win-arm64.zip
          asset_name: stellaris-sav-win-arm64.zip
          asset_content_type: application/zip

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build native executables for Linux
        run: |
          chmod +x ./etc/build-native-linux.sh
          ./etc/build-native-linux.sh
      - name: Upload Linux x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/linux-x64/stellaris-sav-linux-x64.zip
          asset_name: stellaris-sav-linux-x64.zip
          asset_content_type: application/zip
      - name: Upload Linux ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/linux-arm64/stellaris-sav-linux-arm64.zip
          asset_name: stellaris-sav-linux-arm64.zip
          asset_content_type: application/zip

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install macOS workload
        run: dotnet workload install macos
      - name: Build native executables for macOS
        run: |
          chmod +x ./etc/build-native-macos.sh
          ./etc/build-native-macos.sh
      - name: Upload macOS x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/osx-x64/stellaris-sav-osx-x64.zip
          asset_name: stellaris-sav-osx-x64.zip
          asset_content_type: application/zip
      - name: Upload macOS ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/osx-arm64/stellaris-sav-osx-arm64.zip
          asset_name: stellaris-sav-osx-arm64.zip
          asset_content_type: application/zip
