name: Build and Publish Native Executables

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Build native executables for Windows
        run: .\etc\build-native-windows.ps1
      - name: Upload Windows x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/stellaris-sav-win-x64.exe
          asset_name: stellaris-sav-win-x64.exe
          asset_content_type: application/octet-stream
      - name: Upload Windows ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/stellaris-sav-win-arm64.exe
          asset_name: stellaris-sav-win-arm64.exe
          asset_content_type: application/octet-stream

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Linux x64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./etc/Dockerfile.linux-cross
          build-args: |
            TARGETARCH=x64
          outputs: type=local,dest=./native-build,from=output

      - name: Build Linux ARM64
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./etc/Dockerfile.linux-cross
          build-args: |
            TARGETARCH=arm64
          outputs: type=local,dest=./native-build,from=output

      - name: List build outputs
        run: ls -la ./native-build/

      - name: Upload Linux x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/stellaris-sav-linux-x64
          asset_name: stellaris-sav-linux-x64
          asset_content_type: application/octet-stream
      - name: Upload Linux ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/stellaris-sav-linux-arm64
          asset_name: stellaris-sav-linux-arm64
          asset_content_type: application/octet-stream

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 9.0.x
      - name: Install macOS workload
        run: dotnet workload install macos
      - name: Build native executables for macOS
        run: |
          chmod +x ./etc/build-native-macos.sh
          ./etc/build-native-macos.sh
      - name: Upload macOS x64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/stellaris-sav-osx-x64
          asset_name: stellaris-sav-osx-x64
          asset_content_type: application/octet-stream
      - name: Upload macOS ARM64 artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./native-build/stellaris-sav-osx-arm64
          asset_name: stellaris-sav-osx-arm64
          asset_content_type: application/octet-stream
