name: Publish Native Executables

on:
  release:
    types: [created]

permissions:
  contents: write
  packages: write

jobs:
  setup-gitversion:
    runs-on: ubuntu-latest
    outputs:
      semVer: ${{ steps.gitversion.outputs.semVer }}
      majorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for GitVersion
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Determine Version
        id: gitversion
        uses: gittools/actions/gitversion/execute@v0
        with:
          useConfigFile: true
          
      - name: Display GitVersion outputs
        run: |
          echo "Major: ${{ steps.gitversion.outputs.major }}"
          echo "Minor: ${{ steps.gitversion.outputs.minor }}"
          echo "Patch: ${{ steps.gitversion.outputs.patch }}"
          echo "SemVer: ${{ steps.gitversion.outputs.semVer }}"
          echo "MajorMinorPatch: ${{ steps.gitversion.outputs.majorMinorPatch }}"

  build-windows:
    needs: setup-gitversion
    runs-on: windows-latest
    strategy:
      matrix:
        rid: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for GitVersion
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview
          global-json-file: ./src/global.json
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Build native executable for Windows
        run: | 
          .\etc\build-native-executable.ps1 -RuntimeIdentifier win-${{ matrix.rid }}
          .\etc\package-native-executable.ps1 -Platform windows `
              -Architecture ${{ matrix.rid }} `
              -InputFile bin\aot-win-${{ matrix.rid }}\paradox-clausewitz-sav.exe
        
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/paradox-clausewitz-sav_${{ needs.setup-gitversion.outputs.majorMinorPatch }}_windows_${{ matrix.rid }}.zip
          asset_name: paradox-clausewitz-sav_${{ needs.setup-gitversion.outputs.majorMinorPatch }}_windows_${{ matrix.rid }}.zip
          asset_content_type: application/zip

  build-linux:
    needs: setup-gitversion
    runs-on: ubuntu-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install PowerShell
        run: |
          # Download the Microsoft repository GPG keys
          wget -q "https://packages.microsoft.com/config/ubuntu/$(lsb_release -rs)/packages-microsoft-prod.deb"
          
          # Register the Microsoft repository GPG keys
          sudo dpkg -i packages-microsoft-prod.deb
          rm packages-microsoft-prod.deb
          
          # Update the list of packages
          sudo apt-get update
          
          # Install PowerShell
          sudo apt-get install -y powershell
          
          # Verify PowerShell is installed
          pwsh --version

      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Set up Docker Buildx
        uses: dagger/dagger-for-github@8.0.0
        with:
          version: "latest"
          call: |
            publish-aot --rid=linux-${{ matrix.arch }} \
            export --path ./bin/aot-linux-${{ matrix.arch }}/paradox-clausewitz-sav \
            --allow-parent-dir-path

      - name: Build & package native executable
        run: |         
          chmod +x ./etc/package-native-executable.ps1  
          ./etc/package-native-executable.ps1 -Platform linux `
              -Architecture ${{ matrix.arch }} `
              -InputFile bin\aot-linux-${{ matrix.arch }}\paradox-clausewitz-sav        
      
      - name: List build outputs
        run: ls -la ./artifacts/

      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/paradox-clausewitz-sav_${{ needs.setup-gitversion.outputs.majorMinorPatch }}_linux_${{ matrix.arch }}.tar.gz
          asset_name: paradox-clausewitz-sav_${{ needs.setup-gitversion.outputs.majorMinorPatch }}_linux_${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip

  build-macos:
    needs: setup-gitversion
    runs-on: macos-latest
    strategy:
      matrix:
        arch: [x64, arm64]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0  # Fetch all history for GitVersion
          
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 10.0.x
          dotnet-quality: preview
          global-json-file: ./src/global.json
          
      - name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v0
        with:
          versionSpec: '5.x'
          
      - name: Install macOS workload
        run: dotnet workload install macos
        
      - name: Install PowerShell
        run: |
          brew install --cask powershell
          echo "PowerShell version:" 
          pwsh --version
          
      - name: Build & package native executable
        run: | 
          chmod +x ./etc/build-native-executable.ps1
          chmod +x ./etc/package-native-executable.ps1
          ./etc/build-native-executable.ps1 -RuntimeIdentifier osx-${{ matrix.arch }}
          ./etc/package-native-executable.ps1 -Platform macos `
              -Architecture ${{ matrix.arch }} `
              -InputFile bin\aot-osx-${{ matrix.arch }}\paradox-clausewitz-sav        
        
      - name: List artifacts
        run: ls -la ./artifacts/
        
      - name: Upload artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./artifacts/paradox-clausewitz-sav_${{ needs.setup-gitversion.outputs.majorMinorPatch }}_macos_${{ matrix.arch }}.tar.gz
          asset_name: paradox-clausewitz-sav_${{ needs.setup-gitversion.outputs.majorMinorPatch }}_macos_${{ matrix.arch }}.tar.gz
          asset_content_type: application/gzip